import os

def inject_in_file(path, search_str, inject_str, append=False):
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    if append:
        content = content + "\n" + inject_str
    else:
        content = content.replace(search_str, search_str + "\n" + inject_str)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)

expressions_h = r"Source\TextureGraphMaterialBridge\Public\TextureGraphMaterialBridgeDesignerExpressions.h"
expressions_cpp = r"Source\TextureGraphMaterialBridge\Private\TextureGraphMaterialBridgeDesignerExpressions.cpp"
transforms_h = r"Source\TextureGraphMaterialBridge\Private\TextureGraphMaterialBridgeDesignerTransforms.h"
transforms_cpp = r"Source\TextureGraphMaterialBridge\Private\TextureGraphMaterialBridgeDesignerTransforms.cpp"

# 1. Update FloodFill node in Expressions.h
ff_output_search = r"""	UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = ""))
	FTG_Texture Output;"""
ff_output_inject = r"""
	UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "Flood Fill Data"))
	FTG_Texture FloodFillData;"""
inject_in_file(expressions_h, ff_output_search, ff_output_inject)

# 2. Update FloodFill node Evaluate in Expressions.cpp
ff_eval_search = r"""	Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateFloodFill(
		InContext->Cycle,
		Output.GetBufferDescriptor(),
		InContext->TargetId,
		Input.RasterBlob,
		static_cast<int32>(OutputMode),
		static_cast<int32>(Connectivity),
		Seed,
		Threshold,
		GradientAngle);"""
ff_eval_inject = r"""
	FloodFillData = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateFloodFill(
		InContext->Cycle,
		FloodFillData.GetBufferDescriptor(),
		InContext->TargetId,
		Input.RasterBlob,
		2, // Force output mode 2 for Flood Fill Data
		static_cast<int32>(Connectivity),
		Seed,
		Threshold,
		GradientAngle);"""
inject_in_file(expressions_cpp, ff_eval_search, ff_eval_inject)

# 3. Add Classes to Expressions.h
new_classes_h = r"""
UCLASS(MinimalAPI) class UTG_Expression_TGMB_FloodFillToRandomGrayscale : public UTG_Expression { GENERATED_BODY() public: TG_DECLARE_EXPRESSION(TG_Category::Filter); virtual void Evaluate(FTG_EvaluationContext* InContext) override; virtual FTG_Name GetDefaultName() const override { return TEXT("Flood Fill to Random Grayscale"); } virtual FText GetTooltipText() const override { return FText::FromString(TEXT("Converts flood fill data to random grayscale.")); } UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "Flood Fill Data")) FTG_Texture Source; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) int32 Seed = 0; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "")) FTG_Texture Output; };
UCLASS(MinimalAPI) class UTG_Expression_TGMB_FloodFillToRandomColor : public UTG_Expression { GENERATED_BODY() public: TG_DECLARE_EXPRESSION(TG_Category::Filter); virtual void Evaluate(FTG_EvaluationContext* InContext) override; virtual FTG_Name GetDefaultName() const override { return TEXT("Flood Fill to Random Color"); } virtual FText GetTooltipText() const override { return FText::FromString(TEXT("Converts flood fill data to random color.")); } UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "Flood Fill Data")) FTG_Texture Source; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) int32 Seed = 0; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "")) FTG_Texture Output; };
UCLASS(MinimalAPI) class UTG_Expression_TGMB_FloodFillToGradient : public UTG_Expression { GENERATED_BODY() public: TG_DECLARE_EXPRESSION(TG_Category::Filter); virtual void Evaluate(FTG_EvaluationContext* InContext) override; virtual FTG_Name GetDefaultName() const override { return TEXT("Flood Fill to Gradient"); } virtual FText GetTooltipText() const override { return FText::FromString(TEXT("Converts flood fill data to gradient.")); } UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "Flood Fill Data")) FTG_Texture Source; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float GradientAngle = 0.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float RotationJitter = 0.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) int32 Seed = 0; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "")) FTG_Texture Output; };
UCLASS(MinimalAPI) class UTG_Expression_TGMB_FloodFillToPosition : public UTG_Expression { GENERATED_BODY() public: TG_DECLARE_EXPRESSION(TG_Category::Filter); virtual void Evaluate(FTG_EvaluationContext* InContext) override; virtual FTG_Name GetDefaultName() const override { return TEXT("Flood Fill to Position"); } virtual FText GetTooltipText() const override { return FText::FromString(TEXT("Converts flood fill data to position.")); } UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "Flood Fill Data")) FTG_Texture Source; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "")) FTG_Texture Output; };
UCLASS(MinimalAPI) class UTG_Expression_TGMB_FloodFillMapper : public UTG_Expression { GENERATED_BODY() public: TG_DECLARE_EXPRESSION(TG_Category::Filter); virtual void Evaluate(FTG_EvaluationContext* InContext) override; virtual FTG_Name GetDefaultName() const override { return TEXT("Flood Fill Mapper"); } virtual FText GetTooltipText() const override { return FText::FromString(TEXT("Maps a texture into flood fill cells.")); } UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "Flood Fill Data")) FTG_Texture Source; UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "Map")) FTG_Texture Map; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "")) FTG_Texture Output; };

UCLASS(MinimalAPI) class UTG_Expression_TGMB_MultiDirectionalWarp : public UTG_Expression { GENERATED_BODY() public: TG_DECLARE_EXPRESSION(TG_Category::Filter); virtual void Evaluate(FTG_EvaluationContext* InContext) override; virtual FTG_Name GetDefaultName() const override { return TEXT("Multi Directional Warp"); } virtual FText GetTooltipText() const override { return FText::FromString(TEXT("Warps input in multiple directions based on mask intensity.")); } UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "")) FTG_Texture Source; UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "Intensity Map")) FTG_Texture Mask; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Intensity = 1.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Rotation = 0.5f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float GradientAngle = 0.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "")) FTG_Texture Output; };
UCLASS(MinimalAPI) class UTG_Expression_TGMB_NonUniformDirectionalWarp : public UTG_Expression { GENERATED_BODY() public: TG_DECLARE_EXPRESSION(TG_Category::Filter); virtual void Evaluate(FTG_EvaluationContext* InContext) override; virtual FTG_Name GetDefaultName() const override { return TEXT("Non-Uniform Directional Warp"); } virtual FText GetTooltipText() const override { return FText::FromString(TEXT("Warps input directionally masked by intensity.")); } UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "")) FTG_Texture Source; UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "Intensity Map")) FTG_Texture Mask; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Intensity = 1.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float GradientAngle = 0.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "")) FTG_Texture Output; };
UCLASS(MinimalAPI) class UTG_Expression_TGMB_DirectionalDistance : public UTG_Expression { GENERATED_BODY() public: TG_DECLARE_EXPRESSION(TG_Category::Filter); virtual void Evaluate(FTG_EvaluationContext* InContext) override; virtual FTG_Name GetDefaultName() const override { return TEXT("Directional Distance"); } virtual FText GetTooltipText() const override { return FText::FromString(TEXT("Computes distance to nearest mask pixel directionally.")); } UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "")) FTG_Texture Source; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Distance = 0.5f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float GradientAngle = 0.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) int32 Samples = 32; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Threshold = 0.5f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "")) FTG_Texture Output; };

UCLASS(MinimalAPI) class UTG_Expression_TGMB_ShapeSplatter : public UTG_Expression { GENERATED_BODY() public: TG_DECLARE_EXPRESSION(TG_Category::Procedural); virtual void Evaluate(FTG_EvaluationContext* InContext) override; virtual FTG_Name GetDefaultName() const override { return TEXT("Shape Splatter"); } virtual FText GetTooltipText() const override { return FText::FromString(TEXT("Splatter shapes along a grid masked by a background map.")); } UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "Pattern")) FTG_Texture Source; UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "Background")) FTG_Texture Mask; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float CountX = 8; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float CountY = 8; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Scale = 1.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Threshold = 0.1f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "")) FTG_Texture Output; };
UCLASS(MinimalAPI) class UTG_Expression_TGMB_Clouds2 : public UTG_Expression { GENERATED_BODY() public: TG_DECLARE_EXPRESSION(TG_Category::Procedural); virtual void Evaluate(FTG_EvaluationContext* InContext) override; virtual FTG_Name GetDefaultName() const override { return TEXT("Clouds 2"); } virtual FText GetTooltipText() const override { return FText::FromString(TEXT("Generates cloud-like noise.")); } UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Scale = 4.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Contrast = 1.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Bias = 0.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) FVector2f Offset = FVector2f::ZeroVector; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) int32 Seed = 0; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "")) FTG_Texture Output; };
UCLASS(MinimalAPI) class UTG_Expression_TGMB_BnWSpots : public UTG_Expression { GENERATED_BODY() public: TG_DECLARE_EXPRESSION(TG_Category::Procedural); virtual void Evaluate(FTG_EvaluationContext* InContext) override; virtual FTG_Name GetDefaultName() const override { return TEXT("BnW Spots"); } virtual FText GetTooltipText() const override { return FText::FromString(TEXT("Generates black and white spots.")); } UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Scale = 4.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Threshold = 0.5f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Smoothness = 0.1f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) FVector2f Offset = FVector2f::ZeroVector; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) int32 Seed = 0; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "")) FTG_Texture Output; };
UCLASS(MinimalAPI) class UTG_Expression_TGMB_GrungeDirt : public UTG_Expression { GENERATED_BODY() public: TG_DECLARE_EXPRESSION(TG_Category::Procedural); virtual void Evaluate(FTG_EvaluationContext* InContext) override; virtual FTG_Name GetDefaultName() const override { return TEXT("Grunge Dirt"); } virtual FText GetTooltipText() const override { return FText::FromString(TEXT("Generates grunge dirt noise.")); } UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Scale = 4.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Contrast = 1.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Bias = 0.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) FVector2f Offset = FVector2f::ZeroVector; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) int32 Seed = 0; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "")) FTG_Texture Output; };

UCLASS(MinimalAPI) class UTG_Expression_TGMB_Highpass : public UTG_Expression { GENERATED_BODY() public: TG_DECLARE_EXPRESSION(TG_Category::Filter); virtual void Evaluate(FTG_EvaluationContext* InContext) override; virtual FTG_Name GetDefaultName() const override { return TEXT("Highpass"); } virtual FText GetTooltipText() const override { return FText::FromString(TEXT("Applies a highpass filter.")); } UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "")) FTG_Texture Source; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Radius = 4.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Contrast = 1.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "")) FTG_Texture Output; };
UCLASS(MinimalAPI) class UTG_Expression_TGMB_LuminanceHighpass : public UTG_Expression { GENERATED_BODY() public: TG_DECLARE_EXPRESSION(TG_Category::Filter); virtual void Evaluate(FTG_EvaluationContext* InContext) override; virtual FTG_Name GetDefaultName() const override { return TEXT("Luminance Highpass"); } virtual FText GetTooltipText() const override { return FText::FromString(TEXT("Applies a luminance highpass filter.")); } UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "")) FTG_Texture Source; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Radius = 4.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Contrast = 1.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "")) FTG_Texture Output; };
UCLASS(MinimalAPI) class UTG_Expression_TGMB_CurvatureSobel : public UTG_Expression { GENERATED_BODY() public: TG_DECLARE_EXPRESSION(TG_Category::Filter); virtual void Evaluate(FTG_EvaluationContext* InContext) override; virtual FTG_Name GetDefaultName() const override { return TEXT("Curvature Sobel"); } virtual FText GetTooltipText() const override { return FText::FromString(TEXT("Computes curvature using Sobel edge detection.")); } UPROPERTY(meta = (TGType = "TG_Input", PinDisplayName = "")) FTG_Texture Source; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Radius = 1.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Setting")) float Intensity = 1.0f; UPROPERTY(EditAnywhere, Category = NoCategory, meta = (TGType = "TG_Output", PinDisplayName = "")) FTG_Texture Output; };
"""
inject_in_file(expressions_h, "", new_classes_h, append=True)

# 4. Add Class Evaluates to Expressions.cpp
new_evals_cpp = r"""
void UTG_Expression_TGMB_FloodFillToRandomGrayscale::Evaluate(FTG_EvaluationContext* InContext) { Super::Evaluate(InContext); Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateSimple1In(InContext->Cycle, Output.GetBufferDescriptor(), InContext->TargetId, Source.RasterBlob, TEXT("TGMB_FloodFillToRandomGrayscale"), 1, Seed, 0, 0); }
void UTG_Expression_TGMB_FloodFillToRandomColor::Evaluate(FTG_EvaluationContext* InContext) { Super::Evaluate(InContext); Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateSimple1In(InContext->Cycle, Output.GetBufferDescriptor(), InContext->TargetId, Source.RasterBlob, TEXT("TGMB_FloodFillToRandomColor"), 2, Seed, 0, 0); }
void UTG_Expression_TGMB_FloodFillToGradient::Evaluate(FTG_EvaluationContext* InContext) { Super::Evaluate(InContext); Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateSimple1In(InContext->Cycle, Output.GetBufferDescriptor(), InContext->TargetId, Source.RasterBlob, TEXT("TGMB_FloodFillToGradient"), 3, Seed, GradientAngle, RotationJitter); }
void UTG_Expression_TGMB_FloodFillToPosition::Evaluate(FTG_EvaluationContext* InContext) { Super::Evaluate(InContext); Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateSimple1In(InContext->Cycle, Output.GetBufferDescriptor(), InContext->TargetId, Source.RasterBlob, TEXT("TGMB_FloodFillToPosition"), 4, 0, 0, 0); }
void UTG_Expression_TGMB_FloodFillMapper::Evaluate(FTG_EvaluationContext* InContext) { Super::Evaluate(InContext); Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateSimple2In(InContext->Cycle, Output.GetBufferDescriptor(), InContext->TargetId, Source.RasterBlob, Map.RasterBlob, TEXT("TGMB_FloodFillMapper"), 0, 0, 0, 0); }
void UTG_Expression_TGMB_MultiDirectionalWarp::Evaluate(FTG_EvaluationContext* InContext) { Super::Evaluate(InContext); Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateSimple2In(InContext->Cycle, Output.GetBufferDescriptor(), InContext->TargetId, Source.RasterBlob, Mask.RasterBlob, TEXT("TGMB_MultiDirectionalWarp"), Intensity, Rotation, GradientAngle, 0); }
void UTG_Expression_TGMB_NonUniformDirectionalWarp::Evaluate(FTG_EvaluationContext* InContext) { Super::Evaluate(InContext); Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateSimple2In(InContext->Cycle, Output.GetBufferDescriptor(), InContext->TargetId, Source.RasterBlob, Mask.RasterBlob, TEXT("TGMB_NonUniformDirectionalWarp"), Intensity, GradientAngle, 0, 0); }
void UTG_Expression_TGMB_DirectionalDistance::Evaluate(FTG_EvaluationContext* InContext) { Super::Evaluate(InContext); Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateSimple1In(InContext->Cycle, Output.GetBufferDescriptor(), InContext->TargetId, Source.RasterBlob, TEXT("TGMB_DirectionalDistance"), Distance, GradientAngle, Samples, Threshold); }
void UTG_Expression_TGMB_ShapeSplatter::Evaluate(FTG_EvaluationContext* InContext) { Super::Evaluate(InContext); Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateSimple2In(InContext->Cycle, Output.GetBufferDescriptor(), InContext->TargetId, Source.RasterBlob, Mask.RasterBlob, TEXT("TGMB_ShapeSplatter"), CountX, CountY, Scale, Threshold); }
void UTG_Expression_TGMB_Clouds2::Evaluate(FTG_EvaluationContext* InContext) { Super::Evaluate(InContext); Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateSimple0In(InContext->Cycle, Output.GetBufferDescriptor(), InContext->TargetId, TEXT("TGMB_Clouds2"), Scale, Contrast, Bias, Offset.X, Offset.Y, Seed); }
void UTG_Expression_TGMB_BnWSpots::Evaluate(FTG_EvaluationContext* InContext) { Super::Evaluate(InContext); Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateSimple0In(InContext->Cycle, Output.GetBufferDescriptor(), InContext->TargetId, TEXT("TGMB_BnWSpots"), Scale, Threshold, Smoothness, Offset.X, Offset.Y, Seed); }
void UTG_Expression_TGMB_GrungeDirt::Evaluate(FTG_EvaluationContext* InContext) { Super::Evaluate(InContext); Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateSimple0In(InContext->Cycle, Output.GetBufferDescriptor(), InContext->TargetId, TEXT("TGMB_GrungeDirt"), Scale, Contrast, Bias, Offset.X, Offset.Y, Seed); }
void UTG_Expression_TGMB_Highpass::Evaluate(FTG_EvaluationContext* InContext) { Super::Evaluate(InContext); Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateSimple1In(InContext->Cycle, Output.GetBufferDescriptor(), InContext->TargetId, Source.RasterBlob, TEXT("TGMB_Highpass"), Radius, Contrast, 0, 0); }
void UTG_Expression_TGMB_LuminanceHighpass::Evaluate(FTG_EvaluationContext* InContext) { Super::Evaluate(InContext); Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateSimple1In(InContext->Cycle, Output.GetBufferDescriptor(), InContext->TargetId, Source.RasterBlob, TEXT("TGMB_LuminanceHighpass"), Radius, Contrast, 0, 0); }
void UTG_Expression_TGMB_CurvatureSobel::Evaluate(FTG_EvaluationContext* InContext) { Super::Evaluate(InContext); Output = UE::TextureGraphMaterialBridge::FDesignerTransforms::CreateSimple1In(InContext->Cycle, Output.GetBufferDescriptor(), InContext->TargetId, Source.RasterBlob, TEXT("TGMB_CurvatureSobel"), Radius, Intensity, 0, 0); }
"""
inject_in_file(expressions_cpp, "", new_evals_cpp, append=True)

# 5. Add Shader Declarations and Transforms to Transforms.h
shaders_h = r"""
class FSH_TGMB_Generic0In : public FSH_Base { public: DECLARE_EXPORTED_GLOBAL_SHADER(FSH_TGMB_Generic0In, UE_API); SHADER_USE_PARAMETER_STRUCT(FSH_TGMB_Generic0In, FSH_Base); BEGIN_SHADER_PARAMETER_STRUCT(FParameters, ) SHADER_PARAMETER_STRUCT(FTileInfo, TileInfo) SHADER_PARAMETER_STRUCT(FStandardSamplerStates, SamplerStates) SHADER_PARAMETER(float, P1) SHADER_PARAMETER(float, P2) SHADER_PARAMETER(float, P3) SHADER_PARAMETER(float, P4) SHADER_PARAMETER(float, P5) SHADER_PARAMETER(float, P6) END_SHADER_PARAMETER_STRUCT() TEXTURE_ENGINE_DEFAULT_PERMUTATION; TEXTUREGRAPH_ENGINE_DEFAULT_COMPILATION_ENV; };
class FSH_TGMB_Generic1In : public FSH_Base { public: DECLARE_EXPORTED_GLOBAL_SHADER(FSH_TGMB_Generic1In, UE_API); SHADER_USE_PARAMETER_STRUCT(FSH_TGMB_Generic1In, FSH_Base); BEGIN_SHADER_PARAMETER_STRUCT(FParameters, ) SHADER_PARAMETER_STRUCT(FTileInfo, TileInfo) SHADER_PARAMETER_STRUCT(FStandardSamplerStates, SamplerStates) SHADER_PARAMETER_TEXTURE(Texture2D, SourceTexture) SHADER_PARAMETER(float, P1) SHADER_PARAMETER(float, P2) SHADER_PARAMETER(float, P3) SHADER_PARAMETER(float, P4) END_SHADER_PARAMETER_STRUCT() TEXTURE_ENGINE_DEFAULT_PERMUTATION; TEXTUREGRAPH_ENGINE_DEFAULT_COMPILATION_ENV; };
class FSH_TGMB_Generic2In : public FSH_Base { public: DECLARE_EXPORTED_GLOBAL_SHADER(FSH_TGMB_Generic2In, UE_API); SHADER_USE_PARAMETER_STRUCT(FSH_TGMB_Generic2In, FSH_Base); BEGIN_SHADER_PARAMETER_STRUCT(FParameters, ) SHADER_PARAMETER_STRUCT(FTileInfo, TileInfo) SHADER_PARAMETER_STRUCT(FStandardSamplerStates, SamplerStates) SHADER_PARAMETER_TEXTURE(Texture2D, SourceTexture) SHADER_PARAMETER_TEXTURE(Texture2D, MaskTexture) SHADER_PARAMETER(float, P1) SHADER_PARAMETER(float, P2) SHADER_PARAMETER(float, P3) SHADER_PARAMETER(float, P4) END_SHADER_PARAMETER_STRUCT() TEXTURE_ENGINE_DEFAULT_PERMUTATION; TEXTUREGRAPH_ENGINE_DEFAULT_COMPILATION_ENV; };
"""

methods_h = r"""
		static TiledBlobPtr CreateSimple0In(MixUpdateCyclePtr Cycle, BufferDescriptor DesiredDesc, int32 TargetId, const TCHAR* Name, float P1, float P2, float P3, float P4, float P5, float P6);
		static TiledBlobPtr CreateSimple1In(MixUpdateCyclePtr Cycle, BufferDescriptor DesiredDesc, int32 TargetId, TiledBlobPtr Source, const TCHAR* Name, float P1, float P2, float P3, float P4);
		static TiledBlobPtr CreateSimple2In(MixUpdateCyclePtr Cycle, BufferDescriptor DesiredDesc, int32 TargetId, TiledBlobPtr Source, TiledBlobPtr Mask, const TCHAR* Name, float P1, float P2, float P3, float P4);
"""
inject_in_file(transforms_h, "class FSH_TGMBTileGenerator", shaders_h + "\nclass FSH_TGMBTileGenerator")
inject_in_file(transforms_h, "static TiledBlobPtr CreateTileGenerator", methods_h + "\n\t\tstatic TiledBlobPtr CreateTileGenerator")

# 6. Add Transform Implementations to Transforms.cpp
impls_cpp = r"""
IMPLEMENT_GLOBAL_SHADER(FSH_TGMB_Generic0In, "/Plugin/TextureGraphMaterialBridge/Expressions/TGMB_DesignerNodes.usf", "FSH_TGMB_Generic0In", SF_Pixel);
IMPLEMENT_GLOBAL_SHADER(FSH_TGMB_Generic1In, "/Plugin/TextureGraphMaterialBridge/Expressions/TGMB_DesignerNodes.usf", "FSH_TGMB_Generic1In", SF_Pixel);
IMPLEMENT_GLOBAL_SHADER(FSH_TGMB_Generic2In, "/Plugin/TextureGraphMaterialBridge/Expressions/TGMB_DesignerNodes.usf", "FSH_TGMB_Generic2In", SF_Pixel);

namespace UE::TextureGraphMaterialBridge {
	TiledBlobPtr FDesignerTransforms::CreateSimple0In(MixUpdateCyclePtr Cycle, BufferDescriptor DesiredDesc, int32 TargetId, const TCHAR* Name, float P1, float P2, float P3, float P4, float P5, float P6) {
		BufferDescriptor Desc = BuildOutputDesc(DesiredDesc);
		FTileInfo TileInfo;
		JobUPtr RenderJob = CreateShaderJob<FSH_TGMB_Generic0In>(Cycle, TargetId, Name);
		RenderJob->AddArg(ARG_TILEINFO(TileInfo, "TileInfo"))->AddArg(ARG_FLOAT(P1, "Scale"))->AddArg(ARG_FLOAT(P2, "Contrast"))->AddArg(ARG_FLOAT(P3, "Bias"))->AddArg(ARG_FLOAT(P4, "OffsetX"))->AddArg(ARG_FLOAT(P5, "OffsetY"))->AddArg(ARG_INT((int)P6, "Seed"));
		// Need to rename P1-P6 mapping to match exact shader parameters. In TGMB_DesignerNodes.usf, they are Scale, Contrast, Bias, OffsetX, OffsetY, Seed, Threshold, Smoothness...
		// Actually let's just use exact shader param names as requested. Wait, we can't map dynamically easily unless we use the global uniform names.
		// The globals in usf are: Scale, Contrast, Bias, OffsetX, OffsetY, Seed, Threshold, Smoothness, Intensity, Rotation, GradientAngle, Distance, Samples, CountX, CountY, RotationJitter.
		// My simple generic won't work well if I don't set the exact uniform names.
	}
}
"""

# I need to stop. A single generic shader class won't compile unless I add the correct permutation macros for the exact function name or pass the specific arguments.
