#include "TextureGraphMaterialBridgeEditorHooks.h"

#if WITH_EDITOR
FTextureGraphMaterialBridgeEditorHooks::FCreateTextureGraphOutputNodeWidget& FTextureGraphMaterialBridgeEditorHooks::OnCreateTextureGraphOutputNodeWidget()
{
	static FCreateTextureGraphOutputNodeWidget CreateTextureGraphOutputNodeWidget;
	return CreateTextureGraphOutputNodeWidget;
}

FTextureGraphMaterialBridgeEditorHooks::FCreateTextureGraphSampleNodeWidget& FTextureGraphMaterialBridgeEditorHooks::OnCreateTextureGraphSampleNodeWidget()
{
	static FCreateTextureGraphSampleNodeWidget CreateTextureGraphSampleNodeWidget;
	return CreateTextureGraphSampleNodeWidget;
}
#endif
